# Generated by Django 6.0.3 on 2026-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_photo_client_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.CharField(
                choices=[('actif', 'Actif'), ('expiré', 'Expiré'), ('bloqué', 'Bloqué')],
                default='actif',
                max_length=10
            ),
        ),
    ]
