# Generated by Django 4.2.2 on 2026-04-13 09:17

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_skip_payment_columns'),
    ]

    operations = [
        # Ajouter les colonnes manquantes à la table Payment existante
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0.00),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('1Mo', '1Mo Classic'), ('Access', 'Access'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
