# Generated by Django 6.0.3 on 2026-04-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(default='Abidjan', max_length=100),
        ),
    ]