# Generated by Django 6.0.3 on 2026-04-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
    ]
