# Generated by Django 4.2.7 on 2026-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20260419_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(default='Douala', max_length=100),
        ),
    ]
