# Generated by Django 6.0.3 on 2026-04-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20260419_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ville',
        ),
    ]
