# Generated by Django 6.0.3 on 2026-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
        migrations.AddField(
            model_name='client',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
