# Generated by Django 4.2.7 on 2026-06-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('1Mo', '1 Mois'), ('Access', 'Access'), ('Premium', 'Premium'), ('VIP', 'VIP')], default='1Mo', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
