# Generated by Django 6.0.3 on 2026-04-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20260412_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prix',
            field=models.CharField(default='1Mo 5000F', max_length=50),
        ),
    ]
