# Generated by Django 6.0.3 on 2026-04-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_prix'),
    ]

    operations = [
    ]
