# Generated by Django 6.0.3 on 2026-04-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('1Mo', '1Mo Classic'), ('Access', 'Access'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
    ]
