# Generated by Django 4.2.2 on 2026-04-13 09:12

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_skip_payment_columns'),
    ]

    operations = [
        # Supprimer la table Payment existante
        migrations.DeleteModel(
            name='Payment',
        ),
        # Recréer la table Payment avec la bonne structure
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=deletion.CASCADE, related_name='payments', to='clients.client')),
                ('username', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('1Mo', '1Mo Classic'), ('Access', 'Access'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
            options={
                'ordering': ['-payment_date'],
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
