# Generated by Django 4.2.2 on 2026-04-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20260412_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0.00),
            preserve_default=False,
        ),
    ]
