# Generated by Django 6.0.3 on 2026-04-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_skip_payment_columns'),
        ('clients', '0009_add_payment_columns'),
    ]

    operations = [
    ]
